### ISSUE TITLE
[Bug] Ansible can't parse generated defaults due to unquoted colons

### ISSUE THREAD

**Issue by s3lph** [telekom-mms/Automated-Ansible-Role-Documentation#119]
### Description

I have some defaults in argument_specs contain strings starting with colons, such as IPv6 addresses. When generating the defaults files with aar-doc, these strings are rendered unquoted.

While strictly speaking this is valid YAML, this is one of the explicit differences between `ruamel.yaml` (which aar-doc uses) and `PyYAML` (which Ansible uses); see also https://yaml.dev/doc/ruamel.yaml/pyyaml/#fixes:

> ## Differences with PyYAML
> ...
> ### Fixes 
> - ruamel.yaml follows the indent keyword argument on scalars when dumping.
> - **ruamel.yaml allows : in plain scalars**, as long as these are not followed by a space (as per the specification)

### Reproduction steps

1. Create a role with e.g. the following `meta/argument_specs.yml` (I copied the relevant parts from my affected role `knot`):
    ```yaml
    argument_specs:
      main:
        version_added: "0.0.1"
        short_description: Install and configure Knot.
        description:
          - "Install and configure the L(Knot,https://www.knot-dns.cz/docs/latest/html/index.html) authoritative namesever."
        author: s3lph
        options:
          knot_server_listen:
            description:
              - "The list of interfaces to listen on."
              - "Host and port are separated with an C(@) sign."
            type: list
            elements: str
            default: ["::@53", "0.0.0.0@53"]
    ```
1. Create a small demo playbook:
    ```yaml
    - name: Demonstrate defaults syntax error
      hosts: localhost
      roles:
        - knot
    ```
1. Create the defaults using aar-doc:
    ```shell-session
    $ aar-doc roles/knot defaults
    ```

### Current Behavior

The following defaults file is generated:

```yaml
---
# Automatically generated by aar-doc
# The list of interfaces to listen on.
# Host and port are separated with an C(@) sign.
knot_server_listen: [::@53, 0.0.0.0@53]
```

Ansible is unable to parse this file:

```shell-session
$ ansible-playbook --syntax-check playbook.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected node content. while parsing a flow node
did not find expected node content
  in "<unicode string>", line 4, column 22

The error appears to be in '.../roles/knot/defaults/main.yml': line 4, column 22, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Host and port are separated with an C(@) sign.
knot_server_listen: [::@53, 0.0.0.0@53]
                     ^ here
This one looks easy to fix. There seems to be an extra unquoted colon in the line
and this is confusing the parser. It was only expecting to find one free
colon. The solution is just add some quotes around the colon, or quote the
entire line after the first colon.

For instance, if the original line was:

    copy: src=file.txt dest=/path/filename:with_colon.txt

It can be written as:

    copy: src=file.txt dest='/path/filename:with_colon.txt'

Or:

    copy: 'src=file.txt dest=/path/filename:with_colon.txt'
```

### Expected Behavior

aar-doc should emit YAML that is parsable by Ansible. Specifically, strings with colons should be emitted quoted:

```yaml
---
# Automatically generated by aar-doc

# The list of interfaces to listen on.
# Host and port are separated with an C(@) sign.
knot_server_listen: ["::@53", 0.0.0.0@53]
```

```shell-session
$ ansible-playbook --syntax-check playbook.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

playbook: playbook.yml
```

### Additional information

Environment:

aar-doc: `2.0.1` installed via pip

Ansible: ansible-core 2.18.2 installed via system package manager:
```
ansible [core 2.18.2]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```
