### ISSUE TITLE
[Bug] aar-doc defaults produces invalid YAML when duming sequence-of-mapping

### ISSUE THREAD

**Issue by s3lph** [telekom-mms/Automated-Ansible-Role-Documentation#120]
### Description

I have some defaults in argument_specs that contain a sequence of mappings (example see below). When these are rendered to the defaults file by `aar-doc defaults`, the lines of a mapping following the first one (that has the sequence's `- ` in front of it) are indented 2 spaces to few.

This is due to the `yaml.indent` setting used by aar-doc, specifically the equal values of the `sequence` and `offset` parameters:
https://github.com/telekom-mms/Automated-Ansible-Role-Documentation/blob/4417c1570b58edf3bc9b9034632b5069ee1dcc8c/aar_doc/defaults.py#L18

The [documentation](https://yaml.dev/doc/ruamel.yaml/detail/#Indentation_of_block_sequences) of `ruamel.yaml` explicitly warns against doing so:

> If the offset equals sequence, there is not enough room for the dash and the space that has to follow it. In that case the element itself would normally be pushed to the next line (and older versions of ruamel.yaml did so). But this is prevented from happening. However the indent level is what is used for calculating the cumulative indent for deeper levels and specifying sequence=3 resp. offset=2, might give correct, but counter-intuitive results.
> 
> **It is best to always have `sequence >= offset + 2` but this is not enforced.** Depending on your structure, not following this advice **might lead to invalid output.**

### Reproduction steps

1. Create a role with e.g. the following `meta/argument_specs.yml` (I copied the relevant parts from my affected role `knot`):
    ```yaml
    argument_specs:
      main:
        version_added: "0.0.1"
        short_description: Install and configure Knot.
        description:
          - "Install and configure the L(Knot,https://www.knot-dns.cz/docs/latest/html/index.html) authoritative namesever."
        author: s3lph
        options:
          knot_log_targets:
            description:
              - Logging configuration of Knot.
            type: list
            elements: dict
            default:
              - target: syslog
                level: info
    ```
1. Create the defaults using aar-doc:
    ```shell-session
    $ aar-doc roles/knot defaults
    ```

### Current Behavior

The following invalid defaults file is generated:

```yaml
---
# Automatically generated by aar-doc
# Logging configuration of Knot.
knot_log_targets:
  - target: syslog
  level: info
```

### Expected Behavior

`aar-doc defaults` should create valid YAML, e.g.:

```yaml
---
# Automatically generated by aar-doc
# Logging configuration of Knot.
knot_log_targets:
  - target: syslog
    level: info
```

### Additional information

Environment:

aar-doc: `2.0.1` installed via pip

Ansible: ansible-core 2.18.2 installed via system package manager:
```
ansible [core 2.18.2]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```
