### ISSUE TITLE
[Question] Is the generation of defaults in the scope of the project?

### ISSUE THREAD

**Issue by moritzrp** [telekom-mms/Automated-Ansible-Role-Documentation#77]
### Question

First of all, I would like to say that this tool is great and already removes a lot of manual effort. So thank you for the work and effort that is being put into it!

At the moment you still need to manually update the defaults for a role. So updating the `meta/argument_specs.yml` is not enough. With bigger roles this can take quite some effort. This makes we wonder, would you see it within the scope of the project to implement a command that takes care of this as well?

With that the workflow would be pretty straight forward:

1. Create the `meta/argument_specs.yml`
2. `aar_doc myrole markdown`
3. `aar_doc myrole defaults`

I'm looking forward to hear your feedback on this topic.

P.S. I would be happy to contribute to this as well.

**Comment by montaropdf** [comment]
Hi @moritzrp,

I am not a maintainer, but, I am not sure to understand your question, could you provide an example?

**Comment by moritzrp** [comment]
Hey @montaropdf ,

sure, let me give a concrete example:

I have a role "myrole". This role contains the usual `meta/main.yml` and `meta/argument_specs.yml`.

Contents of the `meta/argument_specs.yml`:
```yaml
---
argument_specs:
  main:
    short_description: Main entry for myrole
    options:
      myrole_foo:
        type: str
        required: false
        default: some_foo
        description: foo
      myrole_bar:
        type: str
        required: true
        description: bar
  alternate:
    short_description: Alternate entry for myrole
    options:
      myrole_baz:
        type: str
        required: false
        default: some_baz
        description: baz
      myrole_qux:
        type: str
        required: true
        description: qux
```

Since the  `meta/argument_specs.yml` contains our defaults already, I am after is something like `aar_doc myrole defaults`. 

This could generate the `defaults/main.yml`:
```yaml
---
myrole_foo: some_foo
```

And `defaults/alternate.yml`:
```yaml
---
myrole_baz: some_baz
```

But this is not strictly documentation and has some different behavior than the current file generation.

So the question is from my side: Does this fit into the project from the maintainers perspective? Or is this simply not what the project is intended for?
