### ISSUE TITLE
[Bug] Unhandled error when no argument specs are defined

### ISSUE THREAD

**Issue by moritzrp** [telekom-mms/Automated-Ansible-Role-Documentation#87]
### Description

When you run `aar-doc` against a role with `meta/main.yml` but without any defined `argument_specs` you encounter an error.

### Reproduction steps

1. Create a role called "test"
2. Create the `meta/main.yml`:
```yaml
---
galaxy_info:
  role_name: test
  author: person
  description: Some role I have
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: EL
      versions:
        - "9"
        - "8"
  galaxy_tags:
    - linux
dependencies: []
```
3. Run `aar-doc test markdown`

### Current Behavior

You get an error traceback.

### Expected Behavior

The program should exit telling you that you forgot to specify the argument_specs. Ideally hint that it can be added to `meta/main.yml` or `meta/argument_specs.yml`.

## Version
2.0.0

## Cause
KeyError is not handled on `core.py` on line 92
